MAX_FILE_CONTENT_SIZE = 100 # Megabytes
MAX_NUMBER_OF_SUBMISSIONS_PER_USER = 100
MAX_NUMBER_OF_SUBMISSIONS_PER_PAGE = 20
MAX_NUMBER_OF_CONTESTS_PER_PAGE = 10
MAX_NUMBER_OF_PROBLEMS_PER_PAGE = 25

ALLOWED_HOST = ["0.0.0.0", "127.0.0.1", "localhost"]

DATABASE_FILENAME = "database"

PROBLEM_TESTCASE_ROOT_STORAGE = "problems"
JUDGE_SERVER_ROOT_STORAGE = "judges"
LANGUAGE_EXECUTOR_ROOT_STORAGE = "languages"

HTTP_SCHEME = "http"
DOMAIN = "0.0.0.0"
PORT = "80"
FULL_DOMAIN_WITH_SCHEME = "http://127.0.0.1"

# HTTP_SCHEME = "https"
# DOMAIN = "0.0.0.0"
# PORT = "443"
# FULL_DOMAIN_WITH_SCHEME = "https://127.0.0.1"

DEBUG_STATUS = False
USE_SSL_CONTEXT_ON_MAIN_SERVER = False
SSL_CONTEXT = ("server.pem", "server-key.pem")

USE_SOCKETIO_EVENT = True
SSL_VERIFY = False
SAFE_FIRST_START_AFTER_COMPILING = True

SEND_ACTIVATION_EMAIL = True
ACTIVATION_EMAIL_SENDER = ""
SMTP_SENDING_SERVER = ""
SMTP_PORT = 0

MARKDOWN_SAFE_MODE = False

BYPASSED_DEFAULT_CMD_COMMANDS = ["type", "cat"]

SHOW_STANDARD_ERROR = False

VERDICT_COLORS = {"AC": "success", "WA": "danger", "TLE": "secondary", "RTE": "warning", "IR": "warning", "MLE": "warning", "OLE": "danger", "IE": "danger"}